### ISSUE TITLE
Don't Panic when MongoDB master changes

### ISSUE THREAD

**Issue by SteveRuble** [naveego/data_exporter#1]
The replica set elected a new master and the exporter panicked. Here's the stack trace (in reverse order):

/snap/go/1016/src/net/http/server.go:2720 +0x288
created by net/http.(*Server).Serve
net/http.(*conn).serve(0xc4203c5540, 0xd62440, 0xc4201356c0)
/snap/go/1016/src/net/http/server.go:1801 +0x71d
net/http.(*ServeMux).ServeHTTP(0xda2360, 0xd61900, 0xc421282e00, 0xc42017c500)
net/http.serverHandler.ServeHTTP(0xc420434dd0, 0xd61900, 0xc421282e00, 0xc42017c500)
/snap/go/1016/src/net/http/server.go:2254 +0x130
/snap/go/1016/src/net/http/server.go:2619 +0xb4
net/http.HandlerFunc.ServeHTTP(0xc42043a500, 0xd61900, 0xc421282e00, 0xc42017c500)
main.ExporterHandlerFor.func1(0xd61900, 0xc421282e00, 0xc42017c500)
/home/steve/go/src/github.com/naveego/data_exporter/cmd/data_exporter/promhttp.go:36 +0x15d
/snap/go/1016/src/net/http/server.go:1918 +0x44
/home/steve/go/src/github.com/naveego/data_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:596 +0xf4e
github.com/naveego/data_exporter/vendor/github.com/prometheus/client_golang/prometheus.Gatherers.Gather(0xc420c29c28, 0x1, 0x1, 0x7fbf07eaf340, 0xc42182faa0, 0xc420e7be10, 0xc420910dc0, 0xc4204ccf28)
/home/steve/go/src/github.com/naveego/data_exporter/exporter.go:108 +0x477
panic(0x9506e0, 0xd8ecc0)
/snap/go/1016/src/runtime/panic.go:491 +0x283
github.com/naveego/data_exporter.(*exporter).Gather(0xc42182faa0, 0x0, 0x0, 0x0, 0x0, 0x0)
/snap/go/1016/src/net/http/server.go:1697 +0xd0
net/http.(*conn).serve.func1(0xc4203c5540)
goroutine 4548943 [running]:
2018/06/22 20:29:42 http: panic serving 10.42.135.54:48056: runtime error: invalid memory address or nil pointer dereference

**Comment by derekssmith** [comment]
@SteveRuble I believe this is fixed.  Can you confirm?

**Comment by SteveRuble** [comment]
@derekssmith , It's not fixed yet.
